quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('authordetail/<int:author_id>', views.authordetail, name='authordetail'),
    path('migrateDB/', views.migrate_db, name='migrateDB')
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(),
         name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quoteapp/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.DateField()
    born_location = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.quote

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, ModelChoiceField
from .models import Tag, Quote, Author


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, max_length=100, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']


class AuthorForm(ModelForm):

    fullname = CharField(min_length=3, max_length=30, required=True, widget=TextInput())
    born_date = DateField(required=True, widget=DateInput())
    born_location = CharField(min_length=3, max_length=30, required=True, widget=TextInput())
    description = CharField(min_length=3, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes/quoteapp/views.py
import requests
import re
from bs4 import BeautifulSoup
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quote, Author


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'quoteapp/index.html', {"quotes": quotes})


def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/tag.html', {'form': form})

    return render(request, 'quoteapp/tag.html', {'form': TagForm()})


def quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/quote.html', {"tags": tags, 'form': form})

    return render(request, 'quoteapp/quote.html',
                  {"tags": tags, 'form': QuoteForm()})


def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()

            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/author.html', {'form': form})

    return render(request, 'quoteapp/author.html', {'form': AuthorForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quoteapp/detail.html', {"quote": quote})


def authordetail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quoteapp/authordetail.html', {"author": author})


def migrate_db(request):
    parse()
    add_to_db()
    quotes = Quote.objects.all()
    return render(request, 'quoteapp/index.html', {"quotes": quotes})


def add_to_db():
    for a in authors:
        date = datetime.strptime(a["born_date"], "%B %d, %Y")
        try:
            Author.objects.get(fullname=a["fullname"])
        except Author.DoesNotExist:
            Author(fullname=a["fullname"], born_date=date,
                   born_location=a["born_location"], description=a["description"]).save()
        else:
            continue
    for q in quotes_lst:
        try:
            Quote.objects.get(quote=q["quote"])
        except Quote.DoesNotExist:
            print(q["quote"])
            author_for_quote = Author.objects.get(fullname=q["author"])
            Quote(quote=q["quote"], author=author_for_quote).save()
            quote = Quote.objects.get(quote=q["quote"])
            tags = q["tags"]
            for tag in tags:
                try:
                    tag_for_quote = Tag.objects.get(name=tag)
                    quote.tags.add(tag_for_quote)
                except Tag.DoesNotExist:
                    Tag(name=tag).save()
                    made_tag = Tag.objects.get(name=tag)
                    quote.tags.add(made_tag)


def parse():
    for page in range(10):
        response = requests.get(f"{domain}/page/{page + 1}/")
        parse_cards(response)


domain = "https://quotes.toscrape.com"
quotes_lst = []
authors = []
authors_rdy = []


def parse_cards(link):
    soup = BeautifulSoup(link.text, "lxml")
    quotes = soup.find_all("div", class_="quote")
    for quote_card in quotes:
        quote = quote_card.find("span", class_="text").text
        author = quote_card.find("small", class_="author").text
        author = author.replace("-", " ")
        tags_lst = quote_card.find_all("a", class_="tag")
        tags = []
        for tag in tags_lst:
            tags.append(tag.text)
        quote_dict = {"tags": tags, "author": author, "quote": quote}
        quotes_lst.append(quote_dict)
        if author not in authors_rdy:
            link = quote_card.find("a")
            parse_author(f"{domain}{link['href']}")


def parse_author(link):
    response = requests.get(link)
    soup = BeautifulSoup(response.text, "lxml")
    name = soup.find("h3", class_="author-title").text
    name = name.replace("-", " ")
    born_date = soup.find("span", class_="author-born-date").text
    born_loc = soup.find("span", class_="author-born-location").text
    description = soup.find("div", class_="author-description")
    description = description.text.strip()
    pos = re.search("(More: http)", description)
    if pos:
        author = {"fullname": name, "born_date": born_date, "born_location": born_loc,
                  "description": description[:pos.span()[0]]}
    else:
        author = {"fullname": name, "born_date": born_date, "born_location": born_loc,
                  "description": description}
    authors_rdy.append(name)
    authors.append(author)

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/authordetail.html
{% extends "quoteapp/base.html" %} {% block content %}

<h1>{{author.fullname}}</h1>
<p>Born date: <b>{{author.born_date}}</b></p>
<p>Born location: <b>{{author.born_location}}</b></p>
<p>Description: <b>{{author.description}}</b></p>
{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %} {% load extract_tags %} {% block content %}

<p>Quote: <b>{{quote.quote}}</b></p>
<p>Author:
<a href="{% url 'quoteapp:authordetail' quote.author.id %}"
   role="button" class="outline"> {{ quote.author.fullname }} </a>
</p>
<p>Tags: <small> {{ quote.tags|tags }} </small></p>
{% endblock %}

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_superuser %}
        <ul>
            <li><a href="{% url 'quoteapp:quote' %}" role="button">Add Quote</a></li>
            <li><a href="{% url 'quoteapp:author' %}" role="button">Add Author</a></li>
            <li><a href="{% url 'quoteapp:tag' %}" role="button">Add Tag</a></li>
            <li><a href="{% url 'quoteapp:migrateDB' %}" role="button">Migrate DB</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% elif user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quoteapp:quote' %}" role="button">Add Quote</a></li>
            <li><a href="{% url 'quoteapp:author' %}" role="button">Add Author</a></li>
            <li><a href="{% url 'quoteapp:tag' %}" role="button">Add Tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% for quote in quotes %}
    <ul>
        <li>
            <a href="{% url 'quoteapp:detail' quote.id %}" role="button" class="outline"> {{ quote.quote }} </a>
            <a href="{% url 'quoteapp:authordetail' quote.author.id %}"
               role="button" class="outline"> {{ quote.author.fullname }} </a>
        </li>
    </ul>
    {% endfor %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author:
            {{ form.author }}
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}